version: "3.9"
services:
  api:
    build: .
    volumes:
      - .:/code
    ports:
      - "8042:8042"
    environment:
      - DATABASE_HOST=postgresql+asyncpg://postgres:postgres@api-db:5432/apidb
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@api-db:5432/apidb
    depends_on:
      api-db:
        condition: service_healthy


  api-db:
    image: postgres:14
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apidb
    healthcheck:
      test: "exit 0"

